#:schema ./schema.json

id = "trilium-cn"
name = "Trilium Notes (Chinese)"
icon = "https://raw.githubusercontent.com/zadam/trilium/master/images/icon-color.png"
description = "Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases."

[source]
image = "nriver/trilium-cn:latest"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[volumes]]
id = "data"
dir = "/root/trilium-data"

[env]
TRILIUM_DATA_DIR = { default = "/root/trilium-data", readonly = true }
