#:schema ./schema.json

id = "trilium"
name = "Trilium Notes"
icon = "https://raw.githubusercontent.com/zadam/trilium/master/images/icon-color.png"
description = "Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases."

[source]
image = "zadam/trilium:latest"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[volumes]]
id = "data"
dir = "/home/node/trilium-data"

[env]
TRILIUM_DATA_DIR = { default = "/home/node/trilium-data", readonly = true }
